## Numpy: Guide for Begginers

Numerical Python ([Numpy](https://numpy.org/doc/stable/)) is a open source library widely used in science and engieeering. It contains multidimensional array data structures, such as the homogeneus, N-dimensional `ndarray`, and a large library of functions that operates efficiently on these data structures. 

### Import Numpy

First [install Numpy](https://numpy.org/install/), then import using the following code:

In [172]:
import numpy as np

Prefix `np.` distinguishes NumPy feautures from others that have the same name

### What is an "array"?
In informatics an array is a structure for storing and retrieving data. Let's say that is a grid space where each cell stores one 
element od data. A "one-dimesional" array we might viusalize like a list:
| 1 | 5| 0 |  2|
|---|---|---|---|

And a "two-dimensional" array might be visualized like a table:

| 1 | 5| 0 | 2|
|---|---|---|---|
| 3 | 7| 1 | 4 |
| 9 | 8| 0 | 6 |

"n-dimensional array" would be like set of `n` tables stacked as though they were printed on separate pages.Fundamental array is called `ndarray`. 


### Array fundamentals
One way to initialize an array is using python sequence, such as a list:

In [173]:
a = np.array([1, 2, 3, 0, 6, 7, 9]) #create a 1D array
a #visualize the array

array([1, 2, 3, 0, 6, 7, 9])

The index of the first element is 0, the index of the second element is 1, and so on. We can access the elements of the array using the index as follows:

In [174]:
a[0] #access the first element of the array


1

In [175]:
a[3] #access the fourth element of the array

0

Note: remember that NumPy arrays are "o-indexed" so the first element of the array is accesed uing index `0` not `1`

The array is mutable. It means that an element of the array can be changed.

In [176]:
a[0] = 5 #change the first element of the array
a #visualize the array

array([5, 2, 3, 0, 6, 7, 9])

Notice that the first element of the array was `1` and now is `5`

python slice notation `a[:stop]` can be used to access a subarray

In [177]:
a[:3] #access the first three elements of the array


array([5, 2, 3])

Slicing an array returns only a view of the original array. But we mutate the original array using the view.

In [178]:
b = a[3:] #access the last four elements of the array
b #visualize the array

array([0, 6, 7, 9])

Now we can mutate an elment of array b.

In [179]:
b[0] = 100 #change the first element of b
b #visualize the array

array([100,   6,   7,   9])

As `b` was mutated, the original array `a` gets changed.

In [180]:
a

array([  5,   2,   3, 100,   6,   7,   9])

Two-and higher-dimensional arrays can be initialized from nested Python sequences:

In [181]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) #create a 2D array
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In NumPy a dimension of an array is sometimes referred to as an "axis". In the above cell `a` has two "axes".
An element of `a` can be accesed by specifying the index along each axes. For instance element `7` is in row `1` and column `2`.   

In [182]:
a[1,2]


7

### Array attributes

Thi section covers the `ndim`, `shape`, `size`, and `type` attributes of an array.

`ndim` attribute: retrives the number of an array 

In [183]:
a.ndim #get the number of dimensions of the array

2

`a.shape` attribute: Is a tuple of non-negative integers that specifies the number of elements along each dimension. 

In [184]:
a.shape #get the shape of the array, first element is the number of rows, second element is the number of columns


(3, 4)

Check if the number of dimensions is equal to the length of the shape


In [185]:
len(a.shape) == a.ndim 

True

`a.size` attribute: Gets the total number of elements contained in an array.

In [186]:
a.size #get the number of elements in the array 

12

Check if the number of elements in the array is equal to the product of the shape of the array

In [187]:
import math
a.size == math.prod(a.shape) 

True

`a.dtype` attribute: Gets the data type cointained in the array

In [188]:
a.dtype #get the data type of the array

dtype('int32')

Note: Remember that an array is typically homogenoues meaning that they cointains only one type of data.

### How to create a basic array
This section covers `np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()`, and `np.linspace()`.

Besides creating creating an array form a sequence of elements, we can easily create an array filled with `0`'s.

In [189]:
np.zeros(5) #create an array of zeros


array([0., 0., 0., 0., 0.])

In [190]:
np.zeros((2,3)) #create a 2D array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In tha same way an arrays of `1`'s.

In [191]:
np.ones(5) #create an array of ones

array([1., 1., 1., 1., 1.])

In [192]:
np.ones((2,3)) #create a 2D array of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

Or even an empty array!. The function `empty` creates an array wiht random elements depending on the state of the memory, using `empty` over `zeros` is a matter of speed. It just to make sure to fill every element afterwards.

In [193]:
np.empty(5) #create an array of empty elements, the values are random

array([1., 1., 1., 1., 1.])

In [194]:
np.empty((2,3)) #create a 2D array of empty elements, the values are random

array([[1., 1., 1.],
       [1., 1., 1.]])

Also we can create a array that contains an range with a specified spaced intervals.

In [195]:
b = np.arange(5) #create an array of numbers from 0 to 4
print(f"b = {b}")
c = np.arange(2, 9, 2) #create an array of numbers from 2 to 8 with a step of 2
print(f"c = {c}")

b = [0 1 2 3 4]
c = [2 4 6 8]


We can use `np.linspace` to create an array with values spaced linearly in a specified interval:

In [196]:
np.linspace(0, 10, 5) #create an array of 5 numbers from 0 to 10


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

As you noticed the default data type is floating point (`np.float64`), it is also possible to specify the data type using `dtype` keyword.

In [197]:
np.arange(10, dtype=np.int64) #create an array of numbers from 0 to 9 with the data type int64

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

### Adding, removing and sorting elements
This section covers `np.sort()`, `np.concatenate()`

It is simple to sort an array using `np.sort()`. We cna specify the axis, kind of sorting, and order when the function is called.

Let's start with this array:

In [198]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr


array([2, 1, 5, 3, 7, 4, 6, 8])

We can quickly sort the number in ascending order with:

In [199]:
np.sort(arr) #sort the array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [200]:
rr = np.array([[2, 1, 5, 3, 7, 4, 6, 8], [2, 1, 5, 3, 7, 4, 6, 8], [2, 1, 5, 3, 7, 4, 6, 8]]) #create a 2D array
rr

array([[2, 1, 5, 3, 7, 4, 6, 8],
       [2, 1, 5, 3, 7, 4, 6, 8],
       [2, 1, 5, 3, 7, 4, 6, 8]])

In [201]:
np.sort(rr)

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

Using `take_along_axis` in conjunction with `argsort` we can sort along a specified axis.

We can order along first axis (dow)

In [202]:
rr = np.array([[2, 1, 5, 3], [7, 4, 6, 8], [5, 4, 6, 8]]) #create a 2D array
rr

array([[2, 1, 5, 3],
       [7, 4, 6, 8],
       [5, 4, 6, 8]])

In [203]:
ind= np.argsort(rr, axis=0) #sort the array by columns

In [204]:
np.take_along_axis(rr, ind, axis=0) #sort the array along the rows

array([[2, 1, 5, 3],
       [5, 4, 6, 8],
       [7, 4, 6, 8]])

we can order along 2nd axis (across)

In [205]:
rr = np.array([[2, 1, 5, 3], [7, 4, 6, 8], [5, 4, 6, 8]]) #create a 2D array
rr

array([[2, 1, 5, 3],
       [7, 4, 6, 8],
       [5, 4, 6, 8]])

In [206]:
ind = np.argsort(rr, axis = 1) #get the indices that would sort the array along the columns
ind

array([[1, 0, 3, 2],
       [1, 2, 0, 3],
       [1, 0, 2, 3]], dtype=int64)

In [207]:
np.take_along_axis(rr, ind, axis=1) #sort the array along the columns

array([[1, 2, 3, 5],
       [4, 6, 7, 8],
       [4, 5, 6, 8]])

To concatenate we can use `np.concatenate()`

Let's start with these arrays:

In [208]:
a = np.array([1, 2, 3, 4,]) #create a 1D array
b = np.array([5, 6, 7, 8]) #create a 1D array
print(a)
print(b)


[1 2 3 4]
[5 6 7 8]


In [209]:
np.concatenate((a, b)) #concatenate the two arrays

array([1, 2, 3, 4, 5, 6, 7, 8])

Now with 2D arrays:


In [210]:
#create a 2D arrays
x = np.array([[1, 2], [3, 4]]) 
y = np.array([[5, 6]]) 
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]]


In [211]:
np.concatenate((x, y), axis=0) #concatenate the two arrays along the rows

array([[1, 2],
       [3, 4],
       [5, 6]])

### How to know the shape and size of and array?

This section covers `ndarray.ndim`, `ndarray.size`, `ndarray.shape`.

This jupyter notebooks was created by [Inti](https://github.com/IntiToalombo)