## Numpy Practice
Optional Lab01 ML specilization week 2.

Import Numpy package

In [2]:
import numpy as np
import time

### 3.3 Vector creation
Examples of creating vectors 

In [13]:
# Numpy routines which allocate memory adn fill arrays with value
a = np.zeros(4)  # 1D array of 4 zeros
print(f"np.zeros(4): a = {a}, a shape = {a.shape}, a data tye = {a.dtype}")
a = np.zeros((4,)) # 1D array of 4 zeros
print(f"np.zeros((4,)): a = {a}, a shape = {a.shape}, a data tye = {a.dtype}")
a = np.random.random_sample(4) # 1D array of 4 random numbers
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data tye = {a.dtype}")

np.zeros(4): a = [0. 0. 0. 0.], a shape = (4,), a data tye = float64
np.zeros((4,)): a = [0. 0. 0. 0.], a shape = (4,), a data tye = float64
np.random.random_sample(4): a = [0.85427821 0.14852384 0.94928665 0.16748834], a shape = (4,), a data tye = float64


Some data creation routines do not take a shape touple:

In [14]:
# Numpy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.) # 1D array of 4 numbers
print(f"np.arange(4.): a = {a}, a shape = {a.shape}, a data tye = {a.dtype}")
a = np.random.rand(4) # 1D array of 4 random numbers
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data tye = {a.dtype}")

np.arange(4.): a = [0. 1. 2. 3.], a shape = (4,), a data tye = float64
np.random.rand(4): a = [0.55653067 0.28423595 0.19716717 0.69992222], a shape = (4,), a data tye = float64


Numpy arrays values can be specified manually as well

In [15]:
a = np.array([3, 5, 6, 8]) # 1D array of 4 numbers, 3 is an integer
print(f"np.array[3, 5, 6, 8]: a = {a}, a shape = {a.shape}, a data tye = {a.dtype}")
a = np.array([3., 5, 6, 8]) # 1D array of 4 numbers, 3. is a float
print(f"np.array([3., 5, 6, 8]): a = {a}, a shape = {a.shape}, a data tye = {a.dtype}")

np.array[3, 5, 6, 8]: a = [3 5 6 8], a shape = (4,), a data tye = int32
np.array([3., 5, 6, 8]): a = [3. 5. 6. 8.], a shape = (4,), a data tye = float64


These have created a one-dimensional vector `a` with four elements, `a.shape` returns the dimensions. Here we see a.shape = (4, ) indicating 1-D array with `4` elements.


### 3.4 Operations on Vectors
#### Indexing
NumPy offers a very complete set of idexing and slicing capabilities.
`Indexing` it refers to an element by its position within the array.  
`Slicing` means getting a subset of the elements from an array based on their indices.
**Note:** Numpy starts indexing at zero (0) so the 3rd element of a vector **a** is a[2]
To skip to a new line in Jupyter Notebook, you can use two spaces at the end of the line or use the HTML `<br>` tag. Here is the code that would fit at the placeholder:

In [16]:
# vector indexing operations in 1D arrays
a = np.arange(10.)
print(a)
# access to the 2nd element
print(f"a[2].shape: {a[2].shape}, a[2] = {a[2]}, Accesing an element returns a scalar")

# acces to the last element, use negative index counting from the end
print(f"a[-1].shape: {a[-1].shape}, a[-1] = {a[-1]}")

# indexes must me in the range of the array size, otherwise an error is raised
try:
    print(f"a[10]: {a[10]}")
except IndexError as e:
    print(f"IndexError: {e}")

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
a[2].shape: (), a[2] = 2.0, Accesing an element returns a scalar
a[-1].shape: (), a[-1] = 9.0
IndexError: index 10 is out of bounds for axis 0 with size 10


#### Slicing
Slicing allow us to create an array of indices using three parameters (`start;stop:step`). A susbset of values is also valid.

In [ ]:
# Slicing operations
a = np.arange(10.)
print(f"a          = ", a)
# access 5 consecutive elements (start:stop:step)
c = a[2:7:1]
print(f"a[2:7:1]   = ", c)
# acces 3 elements separated by 2 elements
c = a[2:7:2]
print(f"a[2:7:2]   = ", c)
# access all elements index 3 and beyond
c = a[3:]
print(f"a[3:]      = ", c)
# access all elements up to index 3
c = a[:3]
print(f"a[:3]      = ", c)
# access all elements
c = a[:]
print(f"a[:]       = ", c)


a          =  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
a[2:7:1]   =  [2. 3. 4. 5. 6.]
a[2:7:2]   =  [2. 4. 6.]
a[3:]      =  [3. 4. 5. 6. 7. 8. 9.]
a[:3]      =  [0. 1. 2.]
a[:]       =  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### Single vector operations
There are a number of useful operations that involve operations on a single vector.

In [ ]:
a = np.array([1, 2, 3, 4])
print(f"a          = ", a)

# negate elements of a
b = -a
print(f"-a         = ",b)

# sum of all elements of a, returns a scalar
b = np.sum(a)
print(f"np.sum(a)  = ", b)

# mean of all elements of a, returns a scalar
b = np.mean(a)
print(f"np.mean(a) = ",b)

# square of all elements of a
b = a**2
print(f"a**2       = ", b)


a          =  [1 2 3 4]
-a         =  [-1 -2 -3 -4]
np.sum(a)  =  10
np.mean(a) =  2.5
a**2       =  [ 1  4  9 16]


### Vector vector element-wise operations

Numpy arithmetic, logical and comparison also apply to vector as well. These  operators work on an element-by-element basis.

$$ c_i = a_i + b_i $$

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])
print(f"Primary operators work element-wise: ", a + b)

Primary operators work element-wise:  [0 0 6 8]


Noticed that to carry out this operation correctly, the vector must be of the same size.

In [ ]:
# Try a mismatched operation on vectors of different sizes
c = np.array([1, 2, 3])
try:
    d = a + c
except ValueError as e:
    print(f"ValueError: {e}")

ValueError: operands could not be broadcast together with shapes (4,) (3,) 


### Scalar vector operations

A vector can be scaled by a scalar value(number). This scalar multiplies all the elements of the vector 

In [ ]:
a = np.array([1, 2, 3, 4])
print(f"a = ", a)
 # Multiply vector a by a scalar
b = 2*a
print(f"2*a = ", b)


a =  [1 2 3 4]
2*a =  [2 4 6 8]


### Vector Vector dot product

The **dot product** operation is the mainstay of Numpy and Linear Algebra, since it is used extensively in machine Learnign(ML).
The mathematical representation is depicted below:


![vector dot mathematical representation](C1_W2_Lab04_dot_notrans.gif) 

The vector vector dot product multiplies in two element-wise and then sums the results. The vectors involved on the operation must have the same size. 

Let's code an implementation of the dot product below. Using a **for loop** let's implement a fuction which returns the dot product of two vectors. The function to return given inputs $a$ and $b$:
$$ x = \sum_{i=0}^{n-1} a_i b_i$$
 Assuming that $a$ and $b$ are the same shape.

In [11]:
def my_dot(a, b):
    """"
    Compute the dot product of two vectors a and b
    Args:
        a: 1D numpy array, input vector
        b: 1D numpy array, input vector with same size as a
        Returns:
            x (scalar): dot product of a and b 
    """
    if a.shape !=b.shape:
        raise ValueError("Input vector mus be of the same size")
    x = 0
    for i in range(a.shape[0]):
        x += a[i]*b[i]
    return x # scalar value of the dot product

Test 1:

In [24]:
# test 1-D dot product
a = np.array([1, 2, 3, 4])
b = np.array([-1,2 ,-3, 4])
c = my_dot(a,b)
print(f"Dot product of vector a and b:\nmy_dot(a, b)=",c)

Dot product of vector a and b:
my_dot(a, b)= 10


As is expected a scalar value is returned.
But actually is not neccesary to implement the dot product function by ourselves but we can use `np.dot` numpy operator. 

In [28]:
a = np.array([1, 2, 3, 4])
b = np.array([-1,2 ,-3, 4])
c = np.dot(a, b) # numpy dot product
print(f"Dot product of vector a and b:\nnp.dot(a, b)=",c)
c = np.dot(b, a)
print(f"Dot product of vector b and a:\nnp.dot(b, a)=",c)


Dot product of vector a and b:
np.dot(a, b)= 10
Dot product of vector b and a:
np.dot(b, a)= 10


The need for speed: vector vs loop
NumPy improves speed memory efficiency.

In [16]:
np.random.seed(1) # seed the random number generator
a = np.random.rand(10000000)# 1D array of 10^7 random numbers
b = np.random.rand(10000000) # 1D array of 10^7 random numbers

# Calculate the lapsed time for vectorized version
tic = time.time() # capture the start time
c = np.dot(a,b) # numpy dot product
toc = time.time() # capture the end time
print(f"c = np.dot(a,b) \nc = {c:.4f}")
print(f"Vectorized version duration: {(toc-tic):.2f} s or {1000*(toc-tic):.2f} ms")

# Calculate the lapsed time for the non-vectorized version
tic = time.time()
c = my_dot(a,b)
toc = time.time()
print(f"c = my_dot(a,b)\nc = {c:.4f}")
print(f"Non-vectorized (Loop) version duration: {(toc-tic):.2f} s or {1000*(toc-tic):.2f} ms")

# Delete arrays from memory
del(a)
del(b)




c = np.dot(a,b) 
c = 2501072.5817
Vectorized version duration: 0.01 s or 9.00 ms
c = my_dot(a,b)
c = 2501072.5817
Non-vectorized (Loop) version duration: 2.76 s or 2762.23 ms


So, vectorized version of dot operations takes significante less time to compute becausse NumPy uses available data parallelism in the underlying hardware.
This is critical in Machine Learning where datasets are very large.

### Vector vector operations.
* Commonly `X-train` with (m,n) dimension is used to store train data. Here is important to note it is a 2 dimensional array or matrix.
* `w` will be a 1-dimensional vector of shape(n,)
* As in earlier examples it is possible to perform operations by looping through the examples by indexing them. For example: `x[i]` returns a value of shape(n,) a 1-dimensional vector. 
* Consequently operations involving `x[i]` are often vector-vector.  

In [18]:
# Example
X = np.array([[1], [2], [3], [4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape    }")


X[1] has shape (1,)
w has shape (1,)
c has shape ()


## 4. Matrices

### Abstract
Matrices represented with capitol bold leeter **X**, are 2 dimensional arrays with all of its elements of the same type. In ML `m` represents rows and `n` represents columns, then the elements of a matrix can be referenced using two-dimensional index. In math the index goes from `1` to `n`. In CS indexing will run form `0` to `n-1`.
Check matrices representation below:

Code representation
$$
\mathbf{X} = \begin{pmatrix}
x_{0,0} & x_{0,1} & \cdots & x_{0,n-1} \\
x_{1,0} & x_{1,1} & \cdots & x_{1,n-1} \\
\vdots & \vdots & \ddots & \vdots \\
x_{m-1,0} & x_{m-1,1} & \cdots & x_{m-1,n-1} \\
\end{pmatrix}
$$

Common representation in maths.

$$
\mathbf{X} = \begin{pmatrix}
x_{1,1} & x_{1,2} & \cdots & x_{1,n} \\
x_{2,1} & x_{2,2} & \cdots & x_{2,n} \\
\vdots & \vdots & \ddots & \vdots \\
x_{m,1} & x_{m,2} & \cdots & x_{m,n} \\
\end{pmatrix}
$$

### Numpy Arrays in ML
In Machine Learning 2-D matrices are used to hold training data. Trainig data is `m` examples by `n` feautures creating (m,n) array. 

### Matrix Creation

The same functions that created 1-D vectors will create 2-D or n-D arrays.
Below, the shape tuple is provided to achieve a 2-D results. Notice how NumPy uses brackets to denote each dimension. Further will be noticed that NumPy prints one row per line. 

In [8]:
a = np.zeros((1, 5)) # 1D array of 5 zeros
print(f"a = {a}, a shape {a.shape}\n")

b = np.zeros((2,5)) # 2D array of 2 rows and 5 columns
print(f"b = {b}, b shape = {b.shape}\n")

a = np.zeros((2, 1)) # 2D array of 2 rows and 1 column
print(f"a = {a}, a shape = {a.shape}")



a = [[0. 0. 0. 0. 0.]], a shape (1, 5)

b = [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], b shape = (2, 5)

a = [[0.]
 [0.]], a shape = (2, 1)


It is also posible to specify data manually. Dimensions are specified with additional brackets matching the format in the printing above.
 

In [15]:
a = np.array([[1], [3], [5]]) # 2D array of 3 rows and 1 column
print(f"a = {a}, a shape = {a.shape}")

a = np.array([[1],
              [3],
              [5]]) # 2D array of 3 rows and 1 column
print(f"a = {a}, a shape = {a.shape}")


a = [[1]
 [3]
 [5]], a shape = (3, 1)
a = [[1]
 [3]
 [5]], a shape = (3, 1)


## Operations on Matrices

### Indexing
Accesing an element of a matrix can be done using the two indexes [row(m), column(n)]. Acces can return either an element or a row/column.

In [ ]:
a = np.arange(6).reshape(-1,2) # 2D array of 3 rows and 2 columns
print(f"a.shape = {a.shape}, \na = {a}")

# Access an element
print(f"\na[2, 0].shape: {a[2, 0].shape},\na[2, 0] = {a[2, 0]},\ntype(a[2, 0]) = {type(a[2, 0])} accessing an element returns an scalar")

# Access a row
print(f"\na[2].shape: {a[2].shape},\na[2] = {a[2]},\ntype(a[2]) = {type(a[2])}")

a.shape = (3, 2), 
a = [[0 1]
 [2 3]
 [4 5]]

a[2, 0].shape: (),
a[2, 0] = 4,
type(a[2, 0]) = <class 'numpy.int32'> accessing an element returns an scalar

a[2].shape: (2,),
a[2] = [4 5],
type(a[2]) = <class 'numpy.ndarray'>


**Note**: Notice that in the last example accesing a matrix by just specifying a row will retunr a 1-D vector.

### Reshape 
The previous example we used **reshape**  to shape the array. `a = np.arange(6).reshape(-1, 2)`. This line first create a 1-D vector of six elements and then it reshaped that vector into 2-D array using the reshape command. We could have been writen: `a = np.arange(6).reshape(3,2)` to arrive to the same 3 row, 2 column array. 
The `-1` argument tells the routine to compute the number of rows given the size of the array and the number of columns

Let's break it down to a better understanding.

In [56]:
a = np.arange(6) # 1D array of 6 elements
print((f"a ={a}, a shape = {a.shape}")) 
# Reshape the 1-D array to a 2-D array with 3 rows and 2 columns
a = a.reshape(-1,2) # 2D array of 3 rows and 2 columns
print(f"Vector a reshaped\na = {a}, a shape = {a.shape}")

# Reshape the 1-D array to a 2-D array with 3 rows and 2 columns
a = np.arange(6) # 1D array of 6 elements
a = a.reshape(3,2) # 2D array of 3 rows and 2 columns
print(f"Vector a reshaped\na = {a}, a shape = {a.shape}")


# Reshape the 1-D array to a 2-D array with 2 rows and 3 columns
a = np.arange(6) # 1D array of 6 elements
a = a.reshape(2,3)
print(f"\nVector a reshaped\na = {a}, a shape = {a.shape}")

# Reshape the 1-D array to a 2-D array with 2 rows and 3 columns
a = np.arange(6) # 1D array of 6 elements
a = a.reshape(-1,3)
print(f"Vector a reshaped\na = {a}, a shape = {a.shape}")


a =[0 1 2 3 4 5], a shape = (6,)
Vector a reshaped
a = [[0 1]
 [2 3]
 [4 5]], a shape = (3, 2)
Vector a reshaped
a = [[0 1]
 [2 3]
 [4 5]], a shape = (3, 2)

Vector a reshaped
a = [[0 1 2]
 [3 4 5]], a shape = (2, 3)
Vector a reshaped
a = [[0 1 2]
 [3 4 5]], a shape = (2, 3)


### Slicing

Slicing creates an array of indices using a set of three values (start:stop:step). A subset of values is also valid. Let's check some examples.
 

In [71]:
# vector 2-D slicing operations
a = np.arange(20).reshape(-1,10) # 2D array of 2 rows and 10 columns
print(f"a = \n{a}")

# access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], "\na[0, 2:7:1].shape = ", a[0, 2:7:1].shape, "a 1-D array")

# access 5 consecutive elemtes (start:stop:step) in two rows
print("\na[:, 2:7:1] = \n", a[:, 2:7:1], "\na[:, 2:7:1].shape = ", a[:, 2:7:1].shape, "a 2-D array")

# acces all elements
print("\na[:,:] = \n", a[:,:], "\na[:,:].shape = ",a[:,:].shape, "a 2-D array")

# Acces all elements in a row (very common operation)
print("\na[0,:]",a[0,:], "\na[0,:].shape = ", a[0,:].shape, "a 1-D array")

# same as above
print("\na[0] = ", a[0], "\na[0].shape = ", a[0].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] 
a[0, 2:7:1].shape =  (5,) a 1-D array

a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] 
a[:, 2:7:1].shape =  (2, 5) a 2-D array

a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] 
a[:,:].shape =  (2, 10) a 2-D array

a[0,:] [0 1 2 3 4 5 6 7 8 9] 
a[0,:].shape =  (10,) a 1-D array

a[0] =  [0 1 2 3 4 5 6 7 8 9] 
a[0].shape =  (10,) a 1-D array


This jupyter notebooks was created by [Inti](https://github.com/IntiToalombo)